version: '3.8'

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - COMPOSE_HTTP_TIMEOUT=200
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: nhost-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  graphql-engine:
    image: hasura/graphql-engine:v2.20.0
    container_name: graphql-engine
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: nhost-admin-secret
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  pgdata:
